server:
  port: 8081

spring:
  application:
    name: Application-Orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5432/orchestrator_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    
jwt:
  secret: ${JWT_SECRET}

services:
  scoring:
    url: http://localhost:8082
  bureau:
    url: http://localhost:8083
  antifraud:
    url: http://localhost:8084